const projects = [
  {
    title: "Black Hole",
    model: true,
    titleImage: "/assets/images/black_hole.png",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut metus quis dui ultrices iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent sagittis dui a ligula accumsan scelerisque. Duis varius at dui quis gravida. Nullam iaculis, nisi vitae dictum tempor, lorem dolor accumsan sapien, id porta justo libero non tortor. Aenean luctus at quam nec elementum. Morbi ut orci sed felis placerat eleifend quis eget elit. Cras finibus venenatis metus eget lacinia. Duis vehicula placerat lorem, ut facilisis nisi tristique ac. Nullam in ante nulla. Morbi vel vehicula nunc. Nunc fermentum purus sed ex maximus pulvinar. Etiam dictum ante ac nisi dapibus tristique. Sed vel elit sit amet urna aliquam tristique. Cras enim nunc, imperdiet maximus urna sed, consectetur efficitur lacus. In in suscipit lacus. Vivamus efficitur ultrices libero vitae vulputate. Sed at mattis ligula. Ut tempor ultricies accumsan. Morbi ultricies magna nec tortor tincidunt fringilla. Donec convallis risus ac metus luctus cursus. Duis tempus purus odio, ac varius leo aliquam nec. Aliquam dapibus tincidunt lacus, quis elementum dui vehicula et. In non condimentum risus. Nunc vitae lacinia massa. Proin porttitor ultricies nisl, vel imperdiet eros pulvinar quis. Curabitur egestas, lorem vel vestibulum pharetra, sapien enim hendrerit nulla, in rutrum ligula eros a ipsum. Vestibulum in ligula sed metus commodo egestas."
  },
  {
    title: "Bulb Table",
    model: true,
    titleImage: "/assets/images/bulb_table2.png",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut metus quis dui ultrices iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent sagittis dui a ligula accumsan scelerisque. Duis varius at dui quis gravida. Nullam iaculis, nisi vitae dictum tempor, lorem dolor accumsan sapien, id porta justo libero non tortor. Aenean luctus at quam nec elementum. Morbi ut orci sed felis placerat eleifend quis eget elit. Cras finibus venenatis metus eget lacinia. Duis vehicula placerat lorem, ut facilisis nisi tristique ac. Nullam in ante nulla. Morbi vel vehicula nunc. Nunc fermentum purus sed ex maximus pulvinar. Etiam dictum ante ac nisi dapibus tristique. Sed vel elit sit amet urna aliquam tristique. Cras enim nunc, imperdiet maximus urna sed, consectetur efficitur lacus. In in suscipit lacus. Vivamus efficitur ultrices libero vitae vulputate. Sed at mattis ligula. Ut tempor ultricies accumsan. Morbi ultricies magna nec tortor tincidunt fringilla. Donec convallis risus ac metus luctus cursus. Duis tempus purus odio, ac varius leo aliquam nec. Aliquam dapibus tincidunt lacus, quis elementum dui vehicula et. In non condimentum risus. Nunc vitae lacinia massa. Proin porttitor ultricies nisl, vel imperdiet eros pulvinar quis. Curabitur egestas, lorem vel vestibulum pharetra, sapien enim hendrerit nulla, in rutrum ligula eros a ipsum. Vestibulum in ligula sed metus commodo egestas."
  },
  {
    title: "Catwalk",
    model: true,
    titleImage: "/assets/images/catwalk.png",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut metus quis dui ultrices iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent sagittis dui a ligula accumsan scelerisque. Duis varius at dui quis gravida. Nullam iaculis, nisi vitae dictum tempor, lorem dolor accumsan sapien, id porta justo libero non tortor. Aenean luctus at quam nec elementum. Morbi ut orci sed felis placerat eleifend quis eget elit. Cras finibus venenatis metus eget lacinia. Duis vehicula placerat lorem, ut facilisis nisi tristique ac. Nullam in ante nulla. Morbi vel vehicula nunc. Nunc fermentum purus sed ex maximus pulvinar. Etiam dictum ante ac nisi dapibus tristique. Sed vel elit sit amet urna aliquam tristique. Cras enim nunc, imperdiet maximus urna sed, consectetur efficitur lacus. In in suscipit lacus. Vivamus efficitur ultrices libero vitae vulputate. Sed at mattis ligula. Ut tempor ultricies accumsan. Morbi ultricies magna nec tortor tincidunt fringilla. Donec convallis risus ac metus luctus cursus. Duis tempus purus odio, ac varius leo aliquam nec. Aliquam dapibus tincidunt lacus, quis elementum dui vehicula et. In non condimentum risus. Nunc vitae lacinia massa. Proin porttitor ultricies nisl, vel imperdiet eros pulvinar quis. Curabitur egestas, lorem vel vestibulum pharetra, sapien enim hendrerit nulla, in rutrum ligula eros a ipsum. Vestibulum in ligula sed metus commodo egestas."
  },
  {
    title: "Rapier Wand",
    model: true,
    titleImage: "/assets/images/rapier_wand.png",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut metus quis dui ultrices iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent sagittis dui a ligula accumsan scelerisque. Duis varius at dui quis gravida. Nullam iaculis, nisi vitae dictum tempor, lorem dolor accumsan sapien, id porta justo libero non tortor. Aenean luctus at quam nec elementum. Morbi ut orci sed felis placerat eleifend quis eget elit. Cras finibus venenatis metus eget lacinia. Duis vehicula placerat lorem, ut facilisis nisi tristique ac. Nullam in ante nulla. Morbi vel vehicula nunc. Nunc fermentum purus sed ex maximus pulvinar. Etiam dictum ante ac nisi dapibus tristique. Sed vel elit sit amet urna aliquam tristique. Cras enim nunc, imperdiet maximus urna sed, consectetur efficitur lacus. In in suscipit lacus. Vivamus efficitur ultrices libero vitae vulputate. Sed at mattis ligula. Ut tempor ultricies accumsan. Morbi ultricies magna nec tortor tincidunt fringilla. Donec convallis risus ac metus luctus cursus. Duis tempus purus odio, ac varius leo aliquam nec. Aliquam dapibus tincidunt lacus, quis elementum dui vehicula et. In non condimentum risus. Nunc vitae lacinia massa. Proin porttitor ultricies nisl, vel imperdiet eros pulvinar quis. Curabitur egestas, lorem vel vestibulum pharetra, sapien enim hendrerit nulla, in rutrum ligula eros a ipsum. Vestibulum in ligula sed metus commodo egestas."
  },
  {
    title: "Sofa",
    model: true,
    titleImage: "/assets/images/sofa_cloth_sim.png",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut metus quis dui ultrices iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent sagittis dui a ligula accumsan scelerisque. Duis varius at dui quis gravida. Nullam iaculis, nisi vitae dictum tempor, lorem dolor accumsan sapien, id porta justo libero non tortor. Aenean luctus at quam nec elementum. Morbi ut orci sed felis placerat eleifend quis eget elit. Cras finibus venenatis metus eget lacinia. Duis vehicula placerat lorem, ut facilisis nisi tristique ac. Nullam in ante nulla. Morbi vel vehicula nunc. Nunc fermentum purus sed ex maximus pulvinar. Etiam dictum ante ac nisi dapibus tristique. Sed vel elit sit amet urna aliquam tristique. Cras enim nunc, imperdiet maximus urna sed, consectetur efficitur lacus. In in suscipit lacus. Vivamus efficitur ultrices libero vitae vulputate. Sed at mattis ligula. Ut tempor ultricies accumsan. Morbi ultricies magna nec tortor tincidunt fringilla. Donec convallis risus ac metus luctus cursus. Duis tempus purus odio, ac varius leo aliquam nec. Aliquam dapibus tincidunt lacus, quis elementum dui vehicula et. In non condimentum risus. Nunc vitae lacinia massa. Proin porttitor ultricies nisl, vel imperdiet eros pulvinar quis. Curabitur egestas, lorem vel vestibulum pharetra, sapien enim hendrerit nulla, in rutrum ligula eros a ipsum. Vestibulum in ligula sed metus commodo egestas."
  },
  {
    title: "Sonic Screwdrivers",
    model: true,
    titleImage: "/assets/images/sonics.png",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut metus quis dui ultrices iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent sagittis dui a ligula accumsan scelerisque. Duis varius at dui quis gravida. Nullam iaculis, nisi vitae dictum tempor, lorem dolor accumsan sapien, id porta justo libero non tortor. Aenean luctus at quam nec elementum. Morbi ut orci sed felis placerat eleifend quis eget elit. Cras finibus venenatis metus eget lacinia. Duis vehicula placerat lorem, ut facilisis nisi tristique ac. Nullam in ante nulla. Morbi vel vehicula nunc. Nunc fermentum purus sed ex maximus pulvinar. Etiam dictum ante ac nisi dapibus tristique. Sed vel elit sit amet urna aliquam tristique. Cras enim nunc, imperdiet maximus urna sed, consectetur efficitur lacus. In in suscipit lacus. Vivamus efficitur ultrices libero vitae vulputate. Sed at mattis ligula. Ut tempor ultricies accumsan. Morbi ultricies magna nec tortor tincidunt fringilla. Donec convallis risus ac metus luctus cursus. Duis tempus purus odio, ac varius leo aliquam nec. Aliquam dapibus tincidunt lacus, quis elementum dui vehicula et. In non condimentum risus. Nunc vitae lacinia massa. Proin porttitor ultricies nisl, vel imperdiet eros pulvinar quis. Curabitur egestas, lorem vel vestibulum pharetra, sapien enim hendrerit nulla, in rutrum ligula eros a ipsum. Vestibulum in ligula sed metus commodo egestas."
  },
  {
    title: "Wands",
    model: true,
    titleImage: "/assets/images/wands.png",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut metus quis dui ultrices iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent sagittis dui a ligula accumsan scelerisque. Duis varius at dui quis gravida. Nullam iaculis, nisi vitae dictum tempor, lorem dolor accumsan sapien, id porta justo libero non tortor. Aenean luctus at quam nec elementum. Morbi ut orci sed felis placerat eleifend quis eget elit. Cras finibus venenatis metus eget lacinia. Duis vehicula placerat lorem, ut facilisis nisi tristique ac. Nullam in ante nulla. Morbi vel vehicula nunc. Nunc fermentum purus sed ex maximus pulvinar. Etiam dictum ante ac nisi dapibus tristique. Sed vel elit sit amet urna aliquam tristique. Cras enim nunc, imperdiet maximus urna sed, consectetur efficitur lacus. In in suscipit lacus. Vivamus efficitur ultrices libero vitae vulputate. Sed at mattis ligula. Ut tempor ultricies accumsan. Morbi ultricies magna nec tortor tincidunt fringilla. Donec convallis risus ac metus luctus cursus. Duis tempus purus odio, ac varius leo aliquam nec. Aliquam dapibus tincidunt lacus, quis elementum dui vehicula et. In non condimentum risus. Nunc vitae lacinia massa. Proin porttitor ultricies nisl, vel imperdiet eros pulvinar quis. Curabitur egestas, lorem vel vestibulum pharetra, sapien enim hendrerit nulla, in rutrum ligula eros a ipsum. Vestibulum in ligula sed metus commodo egestas."
  },
];

export default projects;